### ISSUE TITLE
Trial mode configuration error

### ISSUE THREAD

**Issue by cirovladimir** [cptactionhank/docker-atlassian-confluence#33]
I'm running the 5.10.8 version with

>docker run --detach --publish 8090:8090 cptactionhank/atlassian-confluence:5.10.8

it starts fine, but when configuring in trial mode it got stuck after pasting the license. In the container it shows the following error:

```
WARNING [ContainerBackgroundProcessor[StandardEngine[Standalone]]] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread "http-nio-8090-exec-4" (id=38) has been active for 62,753 milliseconds (since 10/27/16 5:25 PM) to serve the same request for http://10.40.3.242:8001/setup/setupembeddeddb-default.action and may be stuck (configured threshold for this StuckThreadDetectionValve is 60 seconds). There is/are 1 thread(s) in total that are monitored by this Valve and may be stuck.
 java.lang.Throwable
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
```
server: **Ubuntu 16.04.1 LTS**
>Linux dockerubnt 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

docker version
```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

do you know what could be wrong?

**Comment by cirovladimir** [comment]
I tried on a local machine and it threw the same error, but after a while (I let it running) it continued with the installation process and, finally, I got a working confluence instance. I suppose it had something to do with the internet access.
