### ISSUE TITLE
Database connection problem after upgrading to 6.7.0

### ISSUE THREAD

**Issue by dsteinkopf** [cptactionhank/docker-atlassian-confluence#67]
When trying to upgrade from 6.3.4 to 6.7.0 I have serious problems: One is #66. After having a workaround for this, I am still getting this problem:

After some time after start, the following error is logged in `atlassian-confluence.log`:
```
2018-02-02 10:51:07,567 WARN [C3P0PooledConnectionPoolManager[identityToken->1bqq1ho9tnu9c71agqbvp|3876555f]-HelperThread-#1] [mchange.v2.resourcepool.BasicResourcePool] log com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@51766e99 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:
java.lang.NullPointerException
        at org.postgresql.Driver.parseURL(Driver.java:531)
        at org.postgresql.Driver.acceptsURL(Driver.java:463)
        at java.sql.DriverManager.getDriver(DriverManager.java:299)
        at com.mchange.v2.c3p0.DriverManagerDataSource.driver(DriverManagerDataSource.java:285)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2018-02-02 10:51:07,569 WARN [C3P0PooledConnectionPoolManager[identityToken->1bqq1ho9tnu9c71agqbvp|3876555f]-HelperThread-#1] [mchange.v2.resourcepool.BasicResourcePool] log Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@21d019dd is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
2018-02-02 10:51:07,570 WARN [localhost-startStop-1] [jdbc.env.internal.JdbcEnvironmentInitiator] initiateService HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database!
```

I am still using the HSQL-Database (as this is only a "semi-productive" installation) - but I think this should not be the cause of the problem.

I did some tests to narrow down the problem - with little success :-(
* Docker container (from this repo) with confluence 6.3.4 has NO problem.
* Docker container (from this repo) with confluence 6.7.0 DOES have the problem.
* Self created containers based on `Dockerfile` from this repo v 6.3.4 (f7bc77a1):
  * Everything unchanged - does NOT have the problem (as expected, just to be sure).
  * Version changed to 6.7.0 DOES have the problem.
  * Version changed to 6.4.0 and some other higher versions: All DO have the problem.

Before I begin to migrate the DB to mysql (some work...) I would like to be sure that there is no other cause that is responsible for this problem.

Any idea what to do to solve the problem or get more information?

**Comment by dsteinkopf** [comment]
The most obvious question (read from the stacktrace) is: Why is the postgres driver doing anything in a HSQL-Installation?

**Comment by dsteinkopf** [comment]
problem solved by upgrading confluence to mysql.
